-- MySQL Script generated by MySQL Workbench
-- 05/29/18 22:41:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TutorVirtual
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TutorVirtual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TutorVirtual` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `TutorVirtual` ;

-- -----------------------------------------------------
-- Table `TutorVirtual`.`vocabularioEspanol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TutorVirtual`.`vocabularioEspanol` (
  `idvocabularioEspanol` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `palabraEspanol` VARCHAR(100) NOT NULL COMMENT '',
  `sonidoEspanol` VARCHAR(100) NOT NULL COMMENT '',
  `imagenEspanol` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idvocabularioEspanol`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TutorVirtual`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TutorVirtual`.`modulo` (
  `idmodulo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `moduloespanol` VARCHAR(100) NOT NULL COMMENT '',
  `modulokiche` VARCHAR(100) NOT NULL COMMENT '',
  `moduloingles` VARCHAR(100) NOT NULL COMMENT '',
  `imagenmodulo` VARCHAR(50) NOT NULL COMMENT '',
  `unidad` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idmodulo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TutorVirtual`.`puntuacionesAltas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TutorVirtual`.`puntuacionesAltas` (
  `idpuntuacionesAltas` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreEstudiante` VARCHAR(250) NOT NULL COMMENT '',
  `puntuacion` INT NOT NULL COMMENT '',
  `idioma1` VARCHAR(100) NOT NULL COMMENT '',
  `idioma2` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`idpuntuacionesAltas`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TutorVirtual`.`vocabularioKiche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TutorVirtual`.`vocabularioKiche` (
  `idvocabularioKiche` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `palabraKiche` VARCHAR(100) NOT NULL COMMENT '',
  `sonidokiche` VARCHAR(100) NOT NULL COMMENT '',
  `imagenKiche` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idvocabularioKiche`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TutorVirtual`.`vocabularioIngles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TutorVirtual`.`vocabularioIngles` (
  `idvocabularioIngles` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `palabraIngles` VARCHAR(100) NOT NULL COMMENT '',
  `sonidoIngles` VARCHAR(100) NOT NULL COMMENT '',
  `imagenIngles` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idvocabularioIngles`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TutorVirtual`.`modulolenguas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TutorVirtual`.`modulolenguas` (
  `idmodulolenguas` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idvocabularioIngles` INT NOT NULL COMMENT '',
  `idvocabularioEspanol` INT NOT NULL COMMENT '',
  `idvocabularioKiche` INT NOT NULL COMMENT '',
  `idmodulo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idmodulolenguas`, `idvocabularioIngles`, `idvocabularioEspanol`, `idvocabularioKiche`, `idmodulo`)  COMMENT '',
  INDEX `fk_modulolenguas_vocabularioIngles_idx` (`idvocabularioIngles` ASC)  COMMENT '',
  INDEX `fk_modulolenguas_vocabularioEspañol1_idx` (`idvocabularioEspanol` ASC)  COMMENT '',
  INDEX `fk_modulolenguas_vocabularioKiche1_idx` (`idvocabularioKiche` ASC)  COMMENT '',
  INDEX `fk_modulolenguas_modulo1_idx` (`idmodulo` ASC)  COMMENT '',
  CONSTRAINT `fk_modulolenguas_vocabularioIngles`
    FOREIGN KEY (`idvocabularioIngles`)
    REFERENCES `TutorVirtual`.`vocabularioIngles` (`idvocabularioIngles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modulolenguas_vocabularioEspañol1`
    FOREIGN KEY (`idvocabularioEspanol`)
    REFERENCES `TutorVirtual`.`vocabularioEspanol` (`idvocabularioEspanol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modulolenguas_vocabularioKiche1`
    FOREIGN KEY (`idvocabularioKiche`)
    REFERENCES `TutorVirtual`.`vocabularioKiche` (`idvocabularioKiche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modulolenguas_modulo1`
    FOREIGN KEY (`idmodulo`)
    REFERENCES `TutorVirtual`.`modulo` (`idmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
