INSERT INTO `vocabulariokiche` (`idvocabularioKiche`, `palabraKiche`, `sonidokiche`, `imagenkiche`) VALUES
(1, 'alaxik', '1-alaxik.wav', 'familia.png'),
(2, 'tat', '2-tat.wav', 'padre.png'),
(3, 'nan', '3-nan.wav', 'madre.png'),
(4, 'alk\'wal', 'alk\'wal.wav', 'hijo.png'),
(5, 'alk\'wal', 'alk\'wal.wav', 'hija.png'),
(6, 'tatanol', '6-tatanol.wav', 'abuelo.png'),
(7, 'ati\'t', '7-ati\'t.wav', 'abuela.png'),
(8, 'inam','8-inam.wav', 'nieto.png'),
(9, 'ikan', '9-ikantio.wav', 'tio.png'),
(10, 'ikaq', '10-ikaq.wav', 'sobrino.png'),
(11, 'ukayib\'al jastaq', '1-ukayib\'al jastaq.wav', 'colores.png'),
(12, 'kaq', '2-kaq.wav', 'rojo.png'),
(13, 'xar', '3-xar.wav', 'azul.png'),
(14, 'rax', '4-rax.wav', 'verde.png'),
(15, 'q\'an.wav', '5-q\'an.wav', 'amarillo.png'),
(16, 'kaqkoj', '6-kaqkoj.wav', 'anaranjado.png'),
(17, 'qako\'r', '7-qako\'r.wav', 'cafe.png'),
(18, 'saq','8-saq.wav', 'blanco.png'),
(19, 'q\'eq', '9-q\'eq.wav', 'negro.png'),
(20, 'chaj', '10-chaj.wav', 'gris.png'),
(21, 'q\'ij', '1-q\'ij.wav', 'dias.png'),
(22, 'nab\'e q\'ij', '2-nab\'e q\'ij.wav', 'domingo.png'),
(23, 'ukab\'q\'ij', '3-ukab\'q\'ij.wav', 'lunes.png'),
(24, 'roxq\'ij', '4-roxq\'ij.wav', 'martes.png'),
(25, 'ukajq\'ij', '5-ukajq\'ij.wav', 'miercoles.png'),
(26, 'ro\'q\'ij', '6-ro\'q\'ij.wav', 'juevez.png'),
(27, 'uwaqq\'ij', '7-uwaqq\'ij.wav', 'viernes.png'),
(28, '8-uwuqq\'ij','8-uwuqq\'ij.wav', 'sabado,png'),
(29, 'ik\'', '9-ik.wav', 'mes.png'),
(30, 'junab\'', '10-junab\'.wav', 'ano.png'),
(31, 'wa\'ix', '2-wa\'ix.wav', 'cero.png'),
(32, 'jun', '3-jun.wav', 'uno.png'),
(33, 'ka\'ib\'', '4-ka\'ib\'.wav', 'dos.png'),
(34, 'oxib\'', '5-oxib\'.wav', 'tres.png'),
(35, 'kajib\'', '6-kajib\'.wav', 'cuatro.png'),
(36, 'job\'', '7-job\'.wav', 'cinco.png'),
(37, 'waqib\'','8-waqib\'.wav', 'seis.png'),
(38, 'wuqub\'', '9-wuqub\'.wav', 'siete.png'),
(39, 'waqxaqib\'', '10-waqxaqib\'.wav', 'ocho.png'),
(40, 'b\'elejeb\'', '10-b\'elejeb\'.wav', 'nueve.png'),

(41, 'jolomaj', '1-jolomaj.wav', 'cabeza.png'),
(42, 'wi\'aj', '2-wi\'aj.wav', 'cabello.png'),
(43, 'b\'oq\'och', '3-b\'oq\'och.wav', 'ojo.png'),
(44, 'tza\'maj', '4-tza\'maj.wav', 'nariz.png'),
(45, 'tab\'al', '5-tab\'al.wav', 'oido.png'),
(46, 'chi\'aj', '6-chi\'aj.wav', 'boca.png'),
(47, 'ware', '7-ware.wav', 'diente.png'),
(48, 'aq\'','8-aq\'.wav', 'lengua.png'),
(49, 'q\'ab\'aj', '9-q\'ab\'aj.wav', 'mano.png'),
(50, 'aqanaj', '10-aqanaj.wav', 'pie.png'),

(51, 'tz\'i\'', '1-tz\'i\'.wav', 'perro.png'),
(52, 'me\'s', '2-me\'s.wav', 'gato.png'),
(53, 'patux', '3-patux.wav', 'pato.png'),
(54, 'tukur', '4-tukur.wav', 'buho.png'),
(55, 'pepe', '5-pepe.wav', 'mariposa.png'),
(56, 'ama\'ak', '6-ama\'ak.wav', 'gallo.png'),
(57, 'ak\'', '7-ak\'.wav', 'gallina.png'),
(58, 'imul','8-imul.wav', 'conejo.png'),
(59, 'kej', '9-kej.wav', 'caballo.png'),
(60, 'aq', '10-aq.wav', 'cerdo.png'),

(61, 'mansa\'n', '1-mansa\'n.wav', 'manzana.png'),
(62, 'tiko\'n', '2-tiko\'n.wav', 'durazno.png'),
(63, 'raxtzu', '3-raxtzu.wav', 'pera.png'),
(64, 'ankane\'y', '4-ankane\'y.wav', 'banano.png'),
(65, 'kaqaq\'oq', '5-kaqaq\'oq.wav', 'sandia.png'),
(66, 'q\'anq\'oq\'', '6-q\'anq\'oq\'.wav', 'melon.png'),
(67, 'kab\'tukan', '7-kab\'tukan.wav', 'fresa.png'),
(68, 'mank','8-mank.wav', 'mango.png'),
(69, 'alanxax', '9-alanxax.wav', 'naranja.png'),
(70, 'q\'anq\'oj q\'oq\'', '10-q\'anq\'oj q\'oq\'.wav', 'papaya.png'),

(71, 'tijob\'al', '1-tijob\'al.wav', 'escuela.png'),
(72, 'k\'amalb\'e', '2-k\'amalb\'e.wav', 'director.png'),
(73, 'ajtij', '3-ajtij.wav', 'maestro.png'),
(74, 'tijoxel', '4-tijoxel.wav', 'estudiante.png'),
(75, 'tem', '5-tem.wav', 'silla.png'),
(76, 'no\'jib\'al wuj', '6-no\'jib\'al wuj.wav', 'libro.png'),
(77, 'wuj re tz\'ib\'anik', '7-wuj re tz\'ib\'anik.wav', 'cuaderno.png'),
(78, 'ajb\'äl','8-ajb\'äl.wav', 'crayon.png'),
(79, 'che\'tz\'ib\'ab\'äl', '9-che\'tz\'ib\'ab\'äl.wav', 'lapiz.png'),
(80, 'tz\'ib\'ab\'al', '10-tz\'ib\'ab\'al.wav', 'lapicero.png'),

(81, 'keqkojxe\'e', '1-keqkojxe\'e.wav', 'zanahoria.png'),
(82, 'tz\'in', '2-tz\'in.wav', 'yuca.png'),
(83, 'saqwach', '3-saqwach.wav', 'papa.png'),
(84, 'pix', '4-pix.wav', 'tomate.png'),
(85, 'sipoyix', '5-sipoyix.wav', 'cebolla.png'),
(86, 'ixim', '6-ixim.wav', 'maiz.png'),
(87, 'oj', '7-oj.wav', 'aguacate.png'),
(88, 'ik','8-ik.wav', 'chile.png'),
(89, 'kyeqichaq', '9-kyeqichaq.wav', 'rabano.png'),
(90, 'k\'ix', '10-k\'ix.wav', 'guisquil.png'),

(91, 'rikil', '1-rikil.wav', 'comida.png'),
(92, 'lej', '2-lej.wav', 'tortilla.png'),
(93, 'kape', '3-kape.wav', 'cafe.png'),
(94, 'saqmo\'l', '4-saqmo\'l.wav', 'huevo.png'),
(95, 'ti\'ij', '5-ti\'ij.wav', 'carne.png'),
(96, 'loq\'om wotz\'otz\'', '6-loq\'om wotz\'otz\'.wav', 'cereal.png'),
(97, 'kaxlanwa', '7-kaxlanwa.wav', 'pan.png'),
(98, 'kinaq\'','8-kinaq\'.wav', 'frijol.png'),
(99, 'al', '9-al.wav', 'pescado.png'),
(100, 'raxkab\'', '10-raxkab\'.wav', 'miel.png'),

(101, 'atz\'iyaq', '1-atz\'iyaq.wav', 'ropa.png'),
(102, 'pawi\'', '2-pawi\'.wav', 'chaleco.png'),
(103, 'rijxa\'', '3-rijxa\'.wav', 'sombrero.png'),
(104, 'xa\'aj', '4-xa\'aj.wav', 'camisa.png'),
(105, 'ixatz\'yaqb\'äl', '5-ixatz\'yaqb\'äl.wav', 'blusa.png'),
(106, 'lix', '6-lix.wav', 'pantalon.png'),
(107, 'kut uq', '7-kut uq.wav', 'falda.png'),
(108, 'meri\'x','8-meri\'x.wav', 'calcetin.png'),
(109, 'xajab\'', '9-xajab\'.wav', 'zapato.png'),
(110, 'tuqxajab\'', '10-tuqxajab\'.wav', 'botas.png'),

(111, 'nik\'owjib\'äl', '1-nik\'owjib\'äl.wav', 'biblioteca.png'),
(112, 'muqub\'al kaminaqib\'', '2-muqub\'al kaminaqib\'.wav', 'cementerio.png'),
(113, 'k\'aykunub\'äl', '3-k\'aykunub\'äl.wav', 'farmacia.png'),
(114, 'k\'ayb\'äl chakub\'äl', '4-k\'ayb\'äl chakub\'äl.wav', 'ferreteria.png'),
(115, 'tyoxaja', '5-tyoxaja.wav', 'iglesia.png'),
(116, 'ja kununib\'äl', '6-ja kununib\'äl.wav', 'hospital.png'),
(117, 'pwaqb\'äl ja', '7-pwaqb\'äl ja.wav', 'banco.png'),
(118, 'suk\'b\'äl ib\'','8-suk\'b\'äl ib\'.wav', 'salon de belleza.png'),
(119, 'wa\'b\'äl', '9-wa\'b\'äl.wav', 'restaurante.png'),
(120, 'k\'ayib\'al', '10-k\'ayib\'al.wav', 'mercado.png'),

(121, 'kajulew','1-kajulew.wav','planeta.png'),
(122, 'ja\'','2-ja\'.wav','rio.png'),
(123, 'ulew','3-ulew.wav','tierra.png'),
(124, 'q\'aq\'','4-q\'aq\'.wav','fuego.png'),
(125, 'kaqiq\'','5-kaqiq\'.wav','aire.png'),
(126, 'raxkyaq\'ab\'','6-raxkyaq\'ab\'.wav','arcoiris.png'),
(127, 'nimaja\'','7-nimaja\'.wav','rio.png'),
(128, 'k\'ache\'aj','8-k\'ache\'aj.wav','bosque.png'),
(129, 'awaj','9-awaj.wav','animal.png'),
(130, 'kotz\'ij','10-kotz\'ij.wav','flor.png'),

(131, 'q\'a\'mja', '1-q\'a\'mja.wav', 'edificio.png'),
(132, 'raqän b\'e', '2-raqän b\'e.wav', 'avenida.png'),
(133, 'nimab\'e', '3-nimab\'e.wav', 'calle.png'),
(134, 'q\'a\'m', '4-q\'a\'m.wav', 'puente.png'),
(135, 'kikbäl', '5-kikbäl.wav', 'estadio.png'),
(136, 'uxlanib\'äl', '6-uxlanib\'äl.wav', 'parque.png'),
(137, 'signals-k\'utb\'e', '7-signals-k\'utb\'e.wav', 'señal de transito.png'),
(138, 'k\'utq\'axb\'äl','8-k\'utq\'axb\'äl.wav', 'semaforo.png'),
(139, 'nim-b\'e', '9-nim-b\'e.wav', 'carretera.png'),
(140, 'k\'utb\'äl wäch', '10-k\'utb\'äl wäch.wav', 'cine.png'),


(141, 'ajyakal ja', '1-ajyakal ja.wav', 'albañil.png'),
(142, 'q\'atöl tzij', '2-q\'atöl tzij.wav', 'juez.png'),
(143, 'chajinel', '3-chajinel.wav', 'policia.png'),
(144, 'ajkun', '4-ajkun.wav', 'doctor.png'),
(145, 'ajk\'amq\'aq\'', '5-ajk\'amq\'aq\'.wav', 'electricista.png'),
(146, 'ajyab\'', '6-ajyab\'.wav', 'enfermera.png'),
(147, 'ajb\'anal wa', '7-ajb\'anal wa.wav', 'cocinero.png'),
(148, 'q\'ojomnel','8-q\'ojomnel.wav', 'musico.png'),
(149, 'nuk\'b\'anel', '9-nuk\'b\'anel.wav', 'programador.png'),
(150, 'ajpuqno\'jibäl', '10-ajpuqno\'jibäl.wav', 'ingeniero.png'),

(151, 'no\'jb\'anem', '1-no\'jb\'anem.wav', 'tecnologia.png'),
(152, 'k\'at', '2-k\'at.wav', 'red.png'),
(153, 'kematz\'ib\'', '3-kematz\'ib\'.wav', 'computadora.png'),
(154, 'ch\'awib\'äl', '4-ch\'awib\'äl.wav', 'telefono.png'),
(155, 'iltz\'ib\'', '5-iltz\'ib\'.wav', 'monitor.png'),
(156, 'taktakb\'äl', '6-taktakb\'äl.wav', 'teclado.png'),
(157, 'nuk\'wäch', '7-nuk\'wäch.wav', 'programa.png'),
(158, 'xib\'ab\'äl k\'ajnak\'', '9-xib\'ab\'äl k\'ajnak\'.wav', 'antivirus.png'),
(159, 'makolob\'', '10-makolob\'.wav', 'inalambrico.png'),
(160, 'sutz\'', '10-sutz\'.wav', 'nube.png');
