INSERT INTO `vocabularioespanol` (`idvocabularioEspanol`, `palabraEspanol`, `sonidoEspanol`, `imagenEspanol`) VALUES
(1, 'Familia', '1-familia.wav', 'familia.png'),
(2, 'Padre', '2-padre.wav', 'padre.png'),
(3, 'Madre', '3-madre.wav', 'madre.png'),
(4, 'Hijo', '4-hijo.wav', 'hijo.png'),
(5, 'Hija', '5-hija.wav', 'hija.png'),
(6, 'Abuelo', '6-abuelo.wav', 'abuelo.png'),
(7, 'Abuela', '7-abuela.wav', 'abuela.png'),
(8, 'Nieto','8-nieto.wav', 'nieto.png'),
(9, 'Tio', '9-tio.wav', 'tio.png'),
(10, 'Sobrino', '10-sobrino.wav', 'sobrino.png'),
(11, 'Colores', '1-colores.wav', 'colores.png'),
(12, 'Rojo', '2-rojo.wav', 'rojo.png'),
(13, 'Azul', '3-azul.wav', 'azul.png'),
(14, 'Verde', '4-verde.wav', 'verde.png'),
(15, 'Amarillo', '5-amarillo.wav', 'amarillo.png'),
(16, 'Anaranjado', '6-anaranjado.wav', 'anaranjado.png'),
(17, 'Cafe', '7-cafe.wav', 'cafe.png'),
(18, 'Blanco','8-blanco.wav', 'blanco.png'),
(19, 'Negro', '9-negro.wav', 'negro.png'),
(20, 'Gris', '10-gris.wav', 'gris.png'),
(21, 'Dias', '1-dias.wav', 'dias.png'),
(22, 'Domingo', '2-domingo.wav', 'domingo.png'),
(23, 'Lunes', '3-lunes.wav', 'lunes.png'),
(24, 'Martes', '4-martes.wav', 'martes.png'),
(25, 'Miercoles', '5-miercoles.wav', 'miercoles.png'),
(26, 'Jueves', '6-jueves.wav', 'juevez.png'),
(27, 'Viernes', '7-viernes.wav', 'viernes.png'),
(28, 'Sabado','8-sabado.wav', 'sabado.png'),
(29, 'Mes', '9-mes.wav', 'mes.png'),
(30, 'Ano', '10-ano.wav', 'ano.png'),
(31, 'Cero', '1-cero.wav', 'cero.png'),
(32, 'Uno', '2-uno.wav', 'uno.png'),
(33, 'Dos', '3-dos.wav', 'dos.png'),
(34, 'Tres', '4-tres.wav', 'tres.png'),
(35, 'Cuatro', '5-cuatro.wav', 'cuatro.png'),
(36, 'Cinco', '6-cinco.wav', 'cinco.png'),
(37, 'Seis','7-seis.wav', 'seis.png'),
(38, 'Siete', '8-siete.wav', 'siete.png'),
(39, 'Ocho', '9--ocho.wav', 'ocho.png'),
(40, 'Nueve', '10-nueve.wav', 'nueve.png'),
(41, 'Cabeza', '1-cabeza.wav', 'cabeza.png'),
(42, 'Cabello', '2-cabello.wav', 'cabello.png'),
(43, 'Ojos', '3-ojos.wav', 'ojo.png'),
(44, 'Nariz', '4-nariz.wav', 'nariz.png'),
(45, 'Oido', '5-oido.wav', 'oido.png'),
(46, 'Boca', '6-boca.wav', 'boca.png'),
(47, 'Diente', '7-diente.wav', 'diente.png'),
(48, 'Lengua','8-lengua.wav', 'lengua.png'),
(49, 'Mano', '9-mano.wav', 'mano.png'),
(50, 'Pie', '10-pie.wav', 'pie.png'),

(51, 'Perro', '1-perro.wav', 'perro.png'),
(52, 'Gato', '2-gato.wav', 'gato.png'),
(53, 'Pato', '3-pato.wav', 'pato.png'),
(54, 'Buho', '4-buho.wav', 'buho.png'),
(55, 'Mariposa', '5-mariposa.wav', 'mariposa.png'),
(56, 'Gallo', '6-gallo.wav', 'gallo.png'),
(57, 'Gallina', '7-gallina.wav', 'gallina.png'),
(58, 'Conejo','8-conejo.wav', 'conejo.png'),
(59, 'Caballo', '9-caballo.wav', 'caballo.png'),
(60, 'Cerdo', '10-cerdo.wav', 'cerdo.png'),
(61, 'Manzana', '1-manzana.wav', 'manzana.png'),
(62, 'Durazno', '2-durazno.wav', 'durazno.png'),
(63, 'Pera', '3-pera.wav', 'pera.png'),
(64, 'Banano', '4-banano.wav', 'banano.png'),
(65, 'Sandia', '5-sandia.wav', 'sandia.png'),
(66, 'Melon', '6-melon.wav', 'melon.png'),
(67, 'Fresa', '7-fresa.wav', 'fresa.png'),
(68, 'Mango','8-mango.wav', 'mango.png'),
(69, 'Naranja', '9-naranja.wav', 'naranja.png'),
(70, 'Papaya', '10-papaya.wav', 'papaya.png'),
(71, 'Escuela', '1-escuela.wav', 'colegio.png'),
(72, 'Director', '2-director.wav', 'director.png'),
(73, 'Maestro', '3-maestro.wav', 'maestro.png'),
(74, 'Estudiante', '4-estudiante.wav', 'Estudiante.png'),
(75, 'Silla', '5-silla.wav', 'silla.png'),
(76, 'Libro', '6-libro.wav', 'libro.png'),
(77, 'Cuaderno', '7-cuaderno.wav', 'cuaderno.png'),
(78, 'Crayon','8-crayon.wav', 'crayon.png'),
(79, 'Lapiz', '9-lapiz.wav', 'lapiz.png'),
(80, 'Lapicero', '10-lapicero.wav', 'lapicero.png'),

(81, 'Zanahoria', '1-zanahoria.wav', 'zanahoria.png'),
(82, 'Yuca', '2-yuca.wav', 'yuca.png'),
(83, 'Papa', '3-papa.wav', 'papa.png'),
(84, 'Tomate', '4-tomate.wav', 'tomate.png'),
(85, 'Cebolla', '5-cebolla.wav', 'cebolla.png'),
(86, 'Maiz', '6-maiz.wav', 'maiz.png'),
(87, 'Aguacate', '7-aguacate.wav', 'aguacate.png'),
(88, 'Chile','8-chile.wav', 'chile.png'),
(89, 'Rabano', '9-rabano.wav', 'rabano.png'),
(90, 'Guisquil', '10-guisquil.wav', 'guisquil.png'),
(91, 'Comida', '1-comida.wav', 'comida.png'),
(92, 'Tortilla', '2-tortilla.wav', 'tortilla.png'),
(93, 'Cafe', '3-cafe.wav', 'cafe.png'),
(94, 'Huevo', '4-huevo.wav', 'huevo.png'),
(95, 'Carne', '5-carne.wav', 'carne.png'),
(96, 'Cereal', '6-cereal.wav', 'cereal.png'),
(97, 'Pan', '7-pan.wav', 'pan.png'),
(98, 'Frijol','8-frijol.wav', 'frijol.png'),
(99, 'Pescado', '9-pescado.wav', 'pescado.png'),
(100, 'Miel', '10-miel.wav', 'miel.png'),

(101, 'Ropa', '1-ropa.wav', 'ropa.png'),
(102, 'Sombrero', '2-sombrero.wav', 'sombrero.png'),
(103, 'Chaleco', '3-chaleco.wav', 'chaleco.png'),
(104, 'Camisa', '4-camisa.wav', 'camisa.png'),
(105, 'Blusa', '5-blusa.wav', 'blusa.png'),
(106, 'Pantalon', '6-pantalon.wav', 'pantalon.png'),
(107, 'Falda', '7-falda.wav', 'falda.png'),
(108, 'Calcetin','8-calcetin.wav', 'calcetin.png'),
(109, 'Zapato', '9-zapato.wav', 'zapato.png'),
(110, 'Botas', '10-botas.wav', 'botas.png'),

(111, 'Biblioteca', '1-biblioteca.wav', 'biblioteca.png'),
(112, 'Cementerio', '2-cementerio.wav', 'cementerio.png'),
(113, 'Farmacia', '3-farmacia.wav', 'farmacia.png'),
(114, 'Ferreteria', '4-ferreteria.wav', 'ferreteria.png'),
(115, 'Iglesia', '5-iglesia.wav', 'iglesia.png'),
(116, 'Hospital', '6-hospital.wav', 'hospital.png'),
(117, 'Banco', '7-banco.wav', 'banco.png'),
(118, 'Salon','8-salon.wav', 'salon de belleza.png'),
(119, 'Restaurante', '9-restaurante.wav', 'restaurante.png'),
(120, 'Mercado', '10-mercado.wav', 'mercado.png'),

(121, 'Planeta', '1-planeta.wav', 'planeta.png'),
(122, 'Agua', '2-agua.wav', 'agua.png'),
(123, 'Tierra', '3-tierra.wav', 'tierra.png'),
(124, 'Fuego', '4-fuego.wav', 'fuego.png'),
(125, 'Aire', '5-aire.wav', 'aire.png'),
(126, 'Arcoiris', '6-arcoiris.wav', 'arcoiris.png'),
(127, 'Rio', '7-rio.wav', 'rio.png'),
(128, 'Bosque','8-bosque.wav', 'bosque.png'),
(129, 'Animal', '9-animal.wav', 'animal.png'),
(130, 'Flor', '10-flor.wav', 'flor.png'),

(131, 'Edificio', '1-edificio.wav', 'edificio.png'),
(132, 'Avenida', '2-avenida.wav', 'avenida.png'),
(133, 'Calle', '3-calle.wav', 'calle.png'),
(134, 'Puente', '4-puente.wav', 'puente.png'),
(135, 'Estadio', '5-estadio.wav', 'estadio.png'),
(136, 'Parque', '6-parque.wav', 'parque.png'),
(137, 'Senal', '7-señal.wav', 'señal de transito.png'),
(138, 'Semaforo','8-semaforo.wav', 'semaforo.png'),
(139, 'Carretera', '9-carretera.wav', 'carretera.png'),
(140, 'Cine', '10-cine.wav', 'cine.png'),

(141, 'Albanil', '1-albañil.wav', 'albañil.png'),
(142, 'Juez', '2-juez.wav', 'juez.png'),
(143, 'Policia', '3-policia.wav', 'policia.png'),
(144, 'Doctor', '4-doctor.wav', 'doctor.png'),
(145, 'Electricista', '5-electricista.wav', 'electricista.png'),
(146, 'Enfermera', '6-enfermera.wav', 'enfermera.png'),
(147, 'Cocinero', '7-cocinero.wav', 'cocinero.png'),
(148, 'Musico','8-musico.wav', 'musico.png'),
(149, 'Programador', '9-programador.wav', 'programador.png'),
(150, 'Ingeniero', '10-ingeniero.wav', 'ingeniero.png'),

(151, 'Tecnologia', '1-tecnologia.wav', 'tecnologia.png'),
(152, 'Red', '2-red.wav', 'red.png'),
(153, 'Computadora', '3-computadora.wav', 'computadora.png'),
(154, 'Telefono', '4-telefono.wav', 'telefono.png'),
(155, 'Monitor', '5-monitor.wav', 'monitor.png'),
(156, 'Teclado', '6-teclado.wav', 'teclado.png'),
(157, 'Programa','7-programa.wav', 'programa.png'),
(158, 'Antivirus', '8-antivirus.wav', 'antivirus.png'),
(159, 'Innalambrico', '9-innalambrico.wav', 'inalambrico.png'),
(160, 'Nube', '10-nube.wav', 'nube.png');
