INSERT INTO `vocabularioIngles` (`idvocabularioIngles`, `palabraIngles`, `sonidoIngles`, `imagenIngles`) VALUES
(1, 'Family', '1-family.m4a', 'familia.png'),
(2, 'Father', '2-father.m4a', 'padre.png'),
(3, 'Mother', '3-mother.m4a', 'madre.png'),
(4, 'Son', '4-son.m4a', 'hijo.png'),
(5, 'Daughter', '5-daughter.m4a', 'hija.png'),
(6, 'Grandfather', '6-grandfather.m4a', 'abuelo.png'),
(7, 'Grandmother', '7-grandmother.m4a', 'abuela.png'),
(8, 'Grandchild', '8-grandchild.m4a', 'nieto.png'),
(9, 'Uncle', '9-uncle.m4a', 'tio.png'),
(10, 'Nephew', '10-nephew.m4a', 'sobrino.png'),
-- Colors
(11, 'Colors', '1-colors.m4a', 'colores.png'),
(12, 'Red', '2-red.m4a', 'rojo.png'),
(13, 'Blue', '3-blue.m4a', 'azul.png'),
(14, 'Green', '4-green.m4a', 'verde.png'),
(15, 'Yellow', '5-yellow.m4a', 'amarillo.png'),
(16, 'Orange', '6-orange.m4a', 'anaranjado.png'),
(17, 'Brown', '7-brown.m4a', 'cafe.png'),
(18, 'White', '8-white.m4a', 'blanco.png'),
(19, 'Black', '9-black.m4a', 'Negro.png'),
(20, 'Gray', '10-gray.m4a', 'gris.png'),
-- Days
(21, 'Day', '1-day.m4a', 'dias.png'),
(22, 'Sunday', '2-sunday.m4a', 'comingo.png'),
(23, 'Monday', '3-monday.m4a', 'lunes.png'),
(24, 'Tuesday', '4-tuesday.m4a', 'martes.png'),
(25, 'Wednesday', '5-wednesday.m4a', 'miercoles.png'),
(26, 'Thursday', '6-thursday.m4a', 'juevez.png'),
(27, 'Friday', '7-friday.m4a', 'viernes.png'),
(28, 'Saturday', '8-saturday.m4a', 'sabado.png'),
(29, 'Month', '9-month.m4a', 'mes.png'),
(30, 'Year', '10-year.m4a', ''),
-- Numbers
(31, 'Zero', '1-zero.m4a', 'cero.png'),
(32, 'One', '2-one.m4a', 'uno.png'),
(33, 'Two', '3-two.m4a', 'dos.png'),
(34, 'Three', '4-three.m4a', 'tres.png'),
(35, 'Four', '5-four.m4a', 'cuatro.png'),
(36, 'Five', '6-five.m4a', 'cinco.png'),
(37, 'Six', '7-six.m4a', 'seis.png'),
(38, 'Seven', '8-seven.m4a', 'siete.png'),
(39, 'Eight', '9-eight.m4a', 'ocho.png'),
(40, 'Nine', '10-nine.m4a', 'nueve.png'),
-- The body
(41, 'Head', '1-head.m4a', 'cabeza.png'),
(42, 'Hair', '2-hair.m4a', 'cabello.png'),
(43, 'Eyes', '3-eyes.m4a', 'ojo.png'),
(44, 'Nose', '4-nose.m4a', 'nariz.png'),
(45, 'Ear', '5-ear.m4a', 'oido.png'),
(46, 'Mouth', '6-mouth.m4a', 'boca.png'),
(47, 'Thooth', '7-thooth.m4a', 'diente.png'),
(48, 'Tongue', '8-tongue.m4a', 'lengua.png'),
(49, 'Hand', '9-hand.m4a', 'mano.png'),
(50, 'Foot', '10-foot.m4a', 'pie.png'),
-- Animals
(51, 'Dog', '1-dog.m4a', 'perro.png'),
(52, 'Cat', '2-cat.m4a', 'gato.png'),
(53, 'Duck', '3-duck.m4a', 'pato.png'),
(54, 'Olw', '4-olw.m4a', 'buho.png'),
(55, 'Butterfly', '5-butterfly.m4a', 'mariposa.png'),
(56, 'Rooster', '6-rooster.m4a', 'gallo.png'),
(57, 'Chicken', '7-chicken.m4a', 'gallina.png'),
(58, 'Rabbit', '8-rabbit.m4a', 'conejo.png'),
(59, 'Horse', '9-horse.m4a', 'caballo.png'),
(60, 'Cerdo', '10-cerdo.m4a', 'cerdo.png'),
-- Fruits
(61, 'Apple', '1-apple.m4a', 'manzana.png'),
(62, 'Peach', '2-peach.m4a', 'durazno.png'),
(63, 'Pear', '3-pear.m4a', 'pera.png'),
(64, 'Banana', '4-banana.m4a', 'banano.png'),
(65, 'Sandia', '5-sandia.m4a', 'sandia.png'),
(66, 'Melon', '6-melon.m4a', 'melon.png'),
(67, 'Strawberry', '7-strawberry.m4a', 'fresa.png'),
(68, 'Mango', '8-mango.m4a', 'mango.png'),
(69, 'Orange', '9-orange.m4a', 'naranja.png'),
(70, 'Papaya', '10-papaya.m4a', 'papaya.png'),
-- School
(71, 'School', '1-school.m4a', 'Colegio.png'),
(72, 'Principal', '2-principal.m4a', 'director.png'),
(73, 'Teacher', '3-teacher.m4a', 'maestro.png'),
(74, 'Student', '4-student.m4a', 'Estudiante.png'),
(75, 'Chair', '5-chair.m4a', 'silla.png'),
(76, 'Book', '6-book.m4a', 'libro.png'),
(77, 'Notebook', '7-notebook.m4a', 'cuaderno.png'),
(78, 'Crayon', '8-crayon.m4a', 'crayon.png'),
(79, 'Pencil', '9-pencil.m4a', 'lapiz.png'),
(80, 'Pen', '10-pen.m4a', 'lapicero.png'),
-- Vegetables
(81, 'Carrot', '1-carrot.m4a', 'zanahoria.png'),
(82, 'Yucca', '2-yucca.m4a', 'yuca.png'),
(83, 'Potato', '3-potato.m4a', 'papa.png'),
(84, 'Tomato', '4-tomato.m4a', 'tomate.png'),
(85, 'Onion', '5-onion.m4a', 'cebolla.png'),
(86, 'Corn', '6-corn.m4a', 'maiz.png'),
(87, 'Avocado', '7-avocado.m4a', 'aguacate.png'),
(88, 'Chile', '8-chile.m4a', 'chile.png'),
(89, 'Radish', '9-radish.m4a', 'rabano.png'),
(90, 'Squash', '10-squash.m4a', 'guisquil.png'),
-- Food
(91, 'Food', '1-food.m4a', 'comida.png'),
(92, 'Tortilla', '2-tortilla.m4a', 'tortilla.png'),
(93, 'Coffee', '3-coffee.m4a', 'cafe.png'),
(94, 'Egg', '4-egg.m4a', 'huevo.png'),
(95, 'Meat', '5-meat.m4a', 'carne.png'),
(96, 'Cereal', '6-cereal.m4a', 'cereal.png'),
(97, 'Bread', '7-bread.m4a', 'pan.png'),
(98, 'Bean', '8-bean.m4a', 'frijol.png'),
(99, 'Al', '9-al.m4a', 'pescado.png'),
(100, 'Honey', '10-honey.m4a', 'miel.png'),
-- Clothes
(101, 'Clothes', '1-clothes.m4a', 'ropa.png'),
(102, 'Hat', '2-hat.m4a', 'sombrero.png'),
(103, 'Vest', '3-vest.m4a', 'chaleco.png'),
(104, 'Shirt', '4-shirt.m4a', 'camisa.png'),
(105, 'Blouse', '5-blouse.m4a', 'blusa.png'),
(106, 'Pants', '6-pants.m4a', 'pantalon.png'),
(107, 'Skirt', '7-skirt.m4a', 'falda.png'),
(108, 'Sock', '8-sock.m4a', 'calcetin.png'),
(109, 'Shoe', '9-shoe.m4a', 'zapato.png'),
(110, 'Boots', '10-boots.m4a', 'botas.png'),
-- Places
(111, 'Library', '1-library.m4a', 'biblioteca.png'),
(112, 'Cementery', '2-cementery.m4a', 'cementerio.png'),
(113, 'Pharmacy', '3-pharmacy.m4a', 'farmacia.png'),
(114, 'Hardware Store', '4-hardware-store.m4a', 'ferreteria.png'),
(115, 'Church', '5-church.m4a', 'iglesia.png'),
(116, 'Hospital', '6-hospital.m4a', 'hospital.png'),
(117, 'Bank', '7-bank.m4a', 'banco.png'),
(118, 'Beauty Salon', '8-beauty-salon.m4a', 'salondebelleza.png'),
(119, 'Restaurant', '9-restaurant.m4a', 'restaurante.png'),
(120, 'Market', '10-market.m4a', 'mercado.png'),
-- Planet
(121, 'Planet', '1-planet.m4a', 'planeta.png'),
(122, 'Water', '2-water.m4a', 'agua.png'),
(123, 'Ground', '3-ground.m4a', 'tierra.png'),
(124, 'Fire', '4-fire.m4a', 'fuego.png'),
(125, 'Air', '5-air.m4a', 'aire.png'),
(126, 'Rainbow', '6-rainbow.m4a', 'arcoiris.png'),
(127, 'River', '7-river.m4a', 'rio.png'),
(128, 'Forest', '8-forest.m4a', 'bosque.png'),
(129, 'Animal', '9-animal.m4a', 'animal.png'),
(130, 'Flower', '10-flower.m4a', 'flor.png'),
-- City
(131, 'Building', '1-building.m4a', 'edificio.png'),
(132, 'Avenue', '2-avenue.m4a', 'avenida.png'),
(133, 'Street', '3-street.m4a', 'calle.png'),
(134, 'Bridge', '4-bridge.m4a', 'puente.png'),
(135, 'Stadium', '5-stadium.m4a', 'estadio.png'),
(136, 'Park', '6-park.m4a', 'parque.png'),
(137, 'Traffic Signals', '7-traffic-signals.m4a', 'señaldetransito.png'),
(138, 'Semaphore', '8-semaphore.m4a', 'semaforo.png'),
(139, 'Road', '9-road.m4a', 'carretera.png'),
(140, 'Cinema', '10-cinema.m4a', 'cine.png'),
-- Professions
(141, 'Builder', '1-builder.m4a', 'albañil.png'),
(142, 'Judge', '2-judge.m4a', 'juez.png'),
(143, 'Police', '3-police.m4a', 'policia.png'),
(144, 'Doctor', '4-doctor.m4a', 'doctor.png'),
(145, 'Electricist', '5-electricist.m4a', 'electricista.png'),
(146, 'Nurse', '6-nurse.m4a', 'enfermera.png'),
(147, 'Chef', '7-chef.m4a', 'cocinero.png'),
(148, 'Musician', '8-musician.m4a', 'musico.png'),
(149, 'Developer', '9-developer.m4a', 'programador.png'),
(150, 'Engineer', '10-engineer.m4a', 'ingeniero.png'),
-- Tech
(151, 'tecnologhy', '1-tecnologhy.m4a', 'tecnologia.png'),
(152, 'network', '2-network.m4a', 'red.png'),
(153, 'computer', '3-computer.m4a', 'computadora.png'),
(154, 'phone', '4-phone.m4a', 'telefono.png'),
(155, 'display', '5-display.m4a', 'monitor.png'),
(156, 'keyboard', '6-keyboard.m4a', 'teclado.png'),
(157, 'software', '7-software.m4a', 'programa.png'),
(158, 'antivirus', '8-antivirus.m4a', 'antivirus.png'),
(159, 'wiriless', '9-wiriless.m4a', 'annalambrico.png'),
(160, 'Cloud', '10-cloud.m4a', 'nube.png');